[variables]
NIXPACKS_PHP_VERSION = "8.2"

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-scripts --no-interaction"]

[start]
cmd = "php artisan migrate --force && php-fpm & nginx -g 'daemon off;'"
